export { default as WelcomeEmail } from "./welcome"
export { default as BookingConfirmedEmail } from "./booking-confirmed"
export { default as BookingPendingEmail } from "./booking-pending"
export { default as BookingApprovedEmail } from "./booking-approved"
export { default as BookingDeclinedEmail } from "./booking-declined"
export { default as SessionReminderEmail } from "./session-reminder"
export { default as BookingCancelledEmail } from "./booking-cancelled"
export { default as ReviewRequestEmail } from "./review-request"
export { default as NewMessageEmail } from "./new-message"
export { default as PasswordResetEmail } from "./password-reset"

// Host emails
export { default as HostWelcomeEmail } from "./host-welcome"
export { default as HostBookingRequestEmail } from "./host-booking-request"
export { default as HostBookingConfirmedEmail } from "./host-booking-confirmed"
export { default as HostCancellationEmail } from "./host-cancellation"
export { default as HostSessionReminderEmail } from "./host-session-reminder"
export { default as HostNewReviewEmail } from "./host-new-review"
export { default as HostPayoutEmail } from "./host-payout"
export { default as HostNewMessageEmail } from "./host-new-message"
